name: Build and Deploy Vue App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23.4.0'

      - name: Install dependencies
        run: npm ci

      - name: Build Vue app
        run: npm run build

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Adding Known Hosts
        run: ssh-keyscan -H vzhurbenko.dev >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync -avz --delete --no-times ./dist/ github-action@vzhurbenko.dev:/var/www/volleyscore.vzhurbenko.dev/
        continue-on-error: true

      - name: Verify deployment
        run: ssh github-action@vzhurbenko.dev 'ls -la /var/www/volleyscore.vzhurbenko.dev/'
